
package com.app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DaoImplService", targetNamespace = "http://dao.app.itea.ua/", wsdlLocation = "http://127.0.0.1:3036/dao?wsdl")
public class DaoImplService
    extends Service
{

    private final static URL DAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DAOIMPLSERVICE_EXCEPTION;
    private final static QName DAOIMPLSERVICE_QNAME = new QName("http://dao.app.itea.ua/", "DaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:3036/dao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DAOIMPLSERVICE_WSDL_LOCATION = url;
        DAOIMPLSERVICE_EXCEPTION = e;
    }

    public DaoImplService() {
        super(__getWsdlLocation(), DAOIMPLSERVICE_QNAME);
    }

    public DaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DAOIMPLSERVICE_QNAME, features);
    }

    public DaoImplService(URL wsdlLocation) {
        super(wsdlLocation, DAOIMPLSERVICE_QNAME);
    }

    public DaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DAOIMPLSERVICE_QNAME, features);
    }

    public DaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DaoImpl
     */
    @WebEndpoint(name = "DaoImplPort")
    public DaoImpl getDaoImplPort() {
        return super.getPort(new QName("http://dao.app.itea.ua/", "DaoImplPort"), DaoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DaoImpl
     */
    @WebEndpoint(name = "DaoImplPort")
    public DaoImpl getDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.app.itea.ua/", "DaoImplPort"), DaoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DAOIMPLSERVICE_EXCEPTION!= null) {
            throw DAOIMPLSERVICE_EXCEPTION;
        }
        return DAOIMPLSERVICE_WSDL_LOCATION;
    }

}
